sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 222936xu
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: ${ALIBABA_CLOUD_ACCESS_KEY_ID}
    accessKeySecret: ${ALIBABA_CLOUD_ACCESS_KEY_SECRET}
    bucketName: sky-take-out-2936
  redis:
    host: localhost
    port: 6379
    auth: 222936
    database: 10
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_APPSECRE}